### ISSUE TITLE
I use Android Studio and After wifi connectivity press next button and close app

### ISSUE THREAD

**Issue by ghost** [hillfly/WifiChat#15]
FATAL EXCEPTION: main
Process: hillfly.wifichat, PID: 31909
java.lang.IllegalArgumentException: The observer is null.
at android.database.Observable.unregisterObserver(Observable.java:64)
at android.support.v4.view.PagerAdapter.unregisterDataSetObserver(PagerAdapter.java:300)
at android.support.v13.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:101)
at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:943)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1091)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
at android.view.View.measure(View.java:17444)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
at android.view.View.measure(View.java:17444)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:447)
at android.view.View.measure(View.java:17444)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2563)
at android.view.View.measure(View.java:17444)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2035)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1200)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1406)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1088)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5825)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:769)
at android.view.Choreographer.doCallbacks(Choreographer.java:582)
at android.view.Choreographer.doFrame(Choreographer.java:552)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:755)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5237)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
![capture](https://cloud.githubusercontent.com/assets/28526449/25801756/be17b6ea-340c-11e7-9b33-f16eb45308a5.PNG)

**Comment by samhith123** [comment]
Detail the issue. I did n't get it.
